name: Auto Tag from Package Version

on:
  push:
    branches:
      - main
    paths:
      - 'sdk/package.json'

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Get package version
        id: package-version
        run: |
          VERSION=$(node -p "require('./sdk/package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: v$VERSION"
        
      - name: Check if tag exists
        id: tag-exists
        run: |
          if git tag --list | grep -q "^${{ steps.package-version.outputs.version }}$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.package-version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag ${{ steps.package-version.outputs.version }} does not exist"
          fi
        
      - name: Create and push tag
        if: steps.tag-exists.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.package-version.outputs.version }}
          git push origin ${{ steps.package-version.outputs.version }}
          echo "Created and pushed tag: ${{ steps.package-version.outputs.version }}"