name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm run clean:install
        working-directory: ./sdk
        
      - name: Build package
        run: npm run build
        working-directory: ./sdk
        
      - name: Setup npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        working-directory: ./sdk
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish to NPM
        run: npm publish
        working-directory: ./sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Cleanup
        if: always()
        run: rm -f .npmrc
        working-directory: ./sdk